#word bank
words = ('ant baboon badger bat bear beaver camel cat clam cobra cougar '
         'coyote crow deer dog donkey duck eagle ferret fox frog goat '
         'goose hawk lion lizard llama mole monkey moose mouse mule newt '
         'otter owl panda parrot pigeon python rabbit ram rat raven '
         'rhino salmon seal shark sheep skunk sloth snake spider '
         'stork swan tiger toad trout turkey turtle weasel whale wolf '
         'wombat zebra '
         'Eagle	Duck Hen Parrot Peacock	Dove Stork Swan '
         'Pigeon Goose Pelican Macaw Parakeet Finches Crow Raven '
         'Vulture Hawk Crane Penguin '
         'Hummingbird Sparrow Woodpecker Hornbill '
         'Owl Myna Cuckoo Turkey '
         'Quail Ostrich Emu Cockatiel '
         'Kingfisher Kite Cockatoo Nightingale '
         'Blue jay Magpie Goldfinch Robin '
         'Swallow Starling Pheasant	Toucan '
         'Canary Seagull '
         'Barnswallow Cassowary Mallard '
         'Falcon Megapode Spoonbill '
         'Ospreys Coot Rail	Budgerigar '
         'WrenLark Sandpiper Arctictern '
         'Passerine Albatross '
         'Moa Kiwi Nightjar Oilbird '
         'Dodo Azuredollar ').split()
letters=['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
